import type { AgentRunSummary, ProjectOverview, TaskStatusSummary } from "./projectTypes.js";
import { taskStatuses, type TaskRecord, type TaskStatus } from "./taskTypes.js";
import type { QualityCheckRecord } from "./qualityTypes.js";

const title = (text: string): string => `# ${text}\n`;

const bullet = (text: string): string => `- ${text}`;

const taskStatusLabels: Record<TaskStatus, string> = {
  backlog: "Backlog",
  ready: "Ready",
  running: "Running",
  needs_review: "Needs Review",
  failed: "Failed",
  blocked: "Blocked",
  done: "Done"
};

const formatTaskSummary = (summary: TaskStatusSummary): string =>
  [
    "| Status | Count |",
    "| --- | ---: |",
    ...taskStatuses.map((status) => `| ${taskStatusLabels[status]} | ${summary[status]} |`),
    `| Total | ${summary.total} |`
  ].join("\n");

const formatTasksByStatus = (tasks: TaskRecord[]): string =>
  taskStatuses
    .map((status) => {
      const matchingTasks = tasks.filter((task) => task.status === status);
      const rows = matchingTasks.length
        ? matchingTasks.map((task) => bullet(`**${task.title}** (${task.priority})`)).join("\n")
        : "- None";

      return `## ${taskStatusLabels[status]}\n\n${rows}`;
    })
    .join("\n\n");

const formatRuns = (runs: AgentRunSummary[]): string =>
  runs.length
    ? runs
        .map((run) =>
          bullet(
            `${run.taskTitle ?? run.command}: ${run.status}${
              run.exitCode === null ? "" : `, exit ${run.exitCode}`
            } (${run.startedAt})`
          )
        )
        .join("\n")
    : "- No runs recorded yet.";

const formatQuality = (checks: QualityCheckRecord[]): string =>
  checks.length
    ? checks
        .map((check) =>
          bullet(
            `${check.label}: ${check.status}, exit ${check.exitCode ?? "none"} (${check.startedAt})`
          )
        )
        .join("\n")
    : "- No quality checks recorded yet.";

export const buildProgressMarkdown = (input: {
  overview: ProjectOverview;
  tasks: TaskRecord[];
  qualityChecks: QualityCheckRecord[];
  generatedAt: string;
}): string => {
  const { overview, tasks, qualityChecks, generatedAt } = input;

  return [
    title(`${overview.project.name} Progress`),
    `Generated by AgentDesk on ${generatedAt}.`,
    "",
    "## Current Stage",
    "",
    `${overview.taskSummary.done} of ${overview.taskSummary.total} tasks are done.`,
    "",
    "## Task Summary",
    "",
    formatTaskSummary(overview.taskSummary),
    "",
    "## Tasks",
    "",
    formatTasksByStatus(tasks),
    "",
    "## Recent Runs",
    "",
    formatRuns(overview.recentRuns),
    "",
    "## Recent Quality Results",
    "",
    formatQuality(qualityChecks),
    ""
  ].join("\n");
};

export const buildDefaultDocumentMarkdown = (input: {
  fileName: string;
  overview: ProjectOverview;
  tasks: TaskRecord[];
  qualityChecks: QualityCheckRecord[];
  generatedAt: string;
}): string => {
  const { fileName, overview, tasks, qualityChecks, generatedAt } = input;
  const projectName = overview.project.name;

  if (fileName === "PROGRESS.md") {
    return buildProgressMarkdown({ overview, tasks, qualityChecks, generatedAt });
  }

  if (fileName === "TASKS.md") {
    return [
      title(`${projectName} Tasks`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Statuses",
      "",
      taskStatuses.map((status) => bullet(status)).join("\n"),
      "",
      formatTasksByStatus(tasks),
      ""
    ].join("\n");
  }

  const sections: Record<string, string> = {
    "README.md": [
      title(projectName),
      "## Overview",
      "",
      "This project is managed locally with AgentDesk.",
      "",
      "## Project Metadata",
      "",
      bullet(`Path: ${overview.project.path}`),
      bullet(`Package manager: ${overview.project.metadata.packageManager}`),
      bullet(`Git branch: ${overview.project.metadata.currentBranch ?? "none"}`),
      ""
    ].join("\n"),
    "PRODUCT.md": `${title(`${projectName} Product`)}\n## Purpose\n\nDescribe the product goal, target users, and MVP scope.\n`,
    "ARCHITECTURE.md": `${title(`${projectName} Architecture`)}\n## Overview\n\nDescribe the major modules, boundaries, and data flow.\n`,
    "DECISIONS.md": `${title(`${projectName} Decisions`)}\n## Decisions\n\n- Record important technical and product decisions here.\n`,
    "TESTING.md": `${title(`${projectName} Testing`)}\n## Quality Commands\n\n${overview.project.metadata.scripts
      .map((script) => bullet(`${script.name}: ${script.command}`))
      .join("\n") || "- No scripts detected."}\n`,
    "SECURITY.md": `${title(`${projectName} Security`)}\n## Security Notes\n\n- Keep local automation visible and user-approved.\n- Do not commit secrets.\n`,
    "AGENTS.md": `${title(`${projectName} Agent Instructions`)}\n## Rules\n\n- Follow task contracts.\n- Keep changes focused.\n- Run quality checks before claiming completion.\n`,
    "PROMPTS.md": `${title(`${projectName} Prompts`)}\n## Prompt Notes\n\nStore reusable implementation, review, fix, test, and security prompts here.\n`,
    "KNOWN_ISSUES.md": `${title(`${projectName} Known Issues`)}\n## Open Issues\n\n- No known issues recorded yet.\n`
  };

  return sections[fileName] ?? `${title(fileName.replace(".md", ""))}\nGenerated by AgentDesk on ${generatedAt}.\n`;
};
