import type { AgentRunSummary, ProjectOverview, TaskStatusSummary } from "./projectTypes.js";
import { taskStatuses, type TaskRecord, type TaskStatus } from "./taskTypes.js";
import type { QualityCheckRecord } from "./qualityTypes.js";

const title = (text: string): string => `# ${text}\n`;

const bullet = (text: string): string => `- ${text}`;

const taskStatusLabels: Record<TaskStatus, string> = {
  backlog: "Backlog",
  ready: "Ready",
  running: "Running",
  needs_review: "Needs Review",
  failed: "Failed",
  blocked: "Blocked",
  done: "Done"
};

const formatTaskSummary = (summary: TaskStatusSummary): string =>
  [
    "| Status | Count |",
    "| --- | ---: |",
    ...taskStatuses.map((status) => `| ${taskStatusLabels[status]} | ${summary[status]} |`),
    `| Total | ${summary.total} |`
  ].join("\n");

const formatTasksByStatus = (tasks: TaskRecord[]): string =>
  taskStatuses
    .map((status) => {
      const matchingTasks = tasks.filter((task) => task.status === status);
      const rows = matchingTasks.length
        ? matchingTasks.map((task) => bullet(`**${task.title}** (${task.priority})`)).join("\n")
        : "- None";

      return `## ${taskStatusLabels[status]}\n\n${rows}`;
    })
    .join("\n\n");

const formatRuns = (runs: AgentRunSummary[]): string =>
  runs.length
    ? runs
        .map((run) =>
          bullet(
            `${run.taskTitle ?? run.command}: ${run.status}${
              run.exitCode === null ? "" : `, exit ${run.exitCode}`
            } (${run.startedAt})`
          )
        )
        .join("\n")
    : "- No runs recorded yet.";

const formatQuality = (checks: QualityCheckRecord[]): string =>
  checks.length
    ? checks
        .map((check) =>
          bullet(
            `${check.label}: ${check.status}, exit ${check.exitCode ?? "none"} (${check.startedAt})`
          )
        )
        .join("\n")
    : "- No quality checks recorded yet.";

const projectMetadataBlock = (overview: ProjectOverview): string =>
  [
    bullet(`Path: ${overview.project.path}`),
    bullet(`Package manager: ${overview.project.metadata.packageManager}`),
    bullet(`Git repo: ${overview.project.metadata.isGitRepo ? "yes" : "no"}`),
    bullet(`Git branch: ${overview.project.metadata.currentBranch ?? "none"}`),
    bullet(`Tasks: ${overview.taskSummary.done} done / ${overview.taskSummary.total} total`)
  ].join("\n");

export const buildProgressMarkdown = (input: {
  overview: ProjectOverview;
  tasks: TaskRecord[];
  qualityChecks: QualityCheckRecord[];
  generatedAt: string;
}): string => {
  const { overview, tasks, qualityChecks, generatedAt } = input;

  return [
    title(`${overview.project.name} Progress`),
    `Generated by AgentDesk on ${generatedAt}.`,
    "",
    "## Current Stage",
    "",
    `${overview.taskSummary.done} of ${overview.taskSummary.total} tasks are done.`,
    overview.nextTask
      ? `Next suggested task: **${overview.nextTask.title}** (${taskStatusLabels[overview.nextTask.status]}).`
      : "No ready task is suggested yet.",
    "",
    "## Task Summary",
    "",
    formatTaskSummary(overview.taskSummary),
    "",
    "## Tasks",
    "",
    formatTasksByStatus(tasks),
    "",
    "## Recent Runs",
    "",
    formatRuns(overview.recentRuns),
    "",
    "## Recent Quality Results",
    "",
    formatQuality(qualityChecks),
    ""
  ].join("\n");
};

export const buildDefaultDocumentMarkdown = (input: {
  fileName: string;
  overview: ProjectOverview;
  tasks: TaskRecord[];
  qualityChecks: QualityCheckRecord[];
  generatedAt: string;
}): string => {
  const { fileName, overview, tasks, qualityChecks, generatedAt } = input;
  const projectName = overview.project.name;
  const metadata = overview.project.metadata;
  const taskSummary = overview.taskSummary;

  if (fileName === "PROGRESS.md") {
    return buildProgressMarkdown({ overview, tasks, qualityChecks, generatedAt });
  }

  if (fileName === "TASKS.md") {
    return [
      title(`${projectName} Tasks`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Summary",
      "",
      formatTaskSummary(taskSummary),
      "",
      "## Statuses",
      "",
      taskStatuses.map((status) => bullet(status)).join("\n"),
      "",
      formatTasksByStatus(tasks),
      ""
    ].join("\n");
  }

  const sections: Record<string, string> = {
    "README.md": [
      title(projectName),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Overview",
      "",
      "This project is managed locally with AgentDesk for task tracking, agent terminals, quality checks, and git review.",
      "",
      "## Project Metadata",
      "",
      projectMetadataBlock(overview),
      "",
      "## Workflow",
      "",
      bullet("Break work into tasks on the board."),
      bullet("Launch agents from a task with a profile."),
      bullet("Run quality checks and review git changes before committing."),
      ""
    ].join("\n"),
    "PRODUCT.md": [
      title(`${projectName} Product`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Purpose",
      "",
      `Describe what ${projectName} delivers, who it serves, and the current MVP scope.`,
      "",
      "## Current Snapshot",
      "",
      projectMetadataBlock(overview),
      overview.nextTask
        ? bullet(`Suggested next focus: ${overview.nextTask.title}`)
        : bullet("No next task is suggested yet."),
      "",
      "## Out of Scope",
      "",
      bullet("Cloud sync and multi-user collaboration."),
      bullet("Marketplace or plugin ecosystem."),
      ""
    ].join("\n"),
    "ARCHITECTURE.md": [
      title(`${projectName} Architecture`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Overview",
      "",
      "Desktop shell with a React renderer, Electron main process, and local SQLite storage.",
      "",
      "## Major Modules",
      "",
      bullet("Projects and metadata detection"),
      bullet("Task board and structured task contracts"),
      bullet("Prompt engine and agent profiles"),
      bullet("PTY terminal engine with persisted run logs"),
      bullet("Quality command runner"),
      bullet("Git status, diff, and local commit workflow"),
      "",
      "## Data",
      "",
      projectMetadataBlock(overview),
      ""
    ].join("\n"),
    "DECISIONS.md": [
      title(`${projectName} Decisions`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Decisions",
      "",
      bullet("Local-first workflow with explicit user confirmation for writes and commits."),
      bullet("Renderer uses preload IPC only; filesystem and shell stay in main."),
      bullet("Task status and run history live in SQLite; PROGRESS.md is previewed before sync."),
      ""
    ].join("\n"),
    "TESTING.md": [
      title(`${projectName} Testing`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Detected Scripts",
      "",
      metadata.scripts.length
        ? metadata.scripts.map((script) => bullet(`${script.name}: \`${script.command}\``)).join("\n")
        : "- No package.json scripts detected.",
      "",
      "## Suggested Quality Flow",
      "",
      bullet("Configure per-project quality commands in AgentDesk."),
      bullet("Run checks after agent work and before git commit."),
      bullet("Create fix tasks from failed checks when needed."),
      ""
    ].join("\n"),
    "SECURITY.md": [
      title(`${projectName} Security`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Principles",
      "",
      bullet("Show commands before agent launch and confirm destructive actions."),
      bullet("Keep Node, filesystem, git, and database access in the main process."),
      bullet("Redact common secret patterns in terminal, quality, and git output."),
      "",
      "## Project Notes",
      "",
      bullet("Do not store API keys in agent profile environment variables."),
      bullet("Review generated markdown before overwriting existing docs."),
      ""
    ].join("\n"),
    "AGENTS.md": [
      title(`${projectName} Agent Instructions`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Rules",
      "",
      bullet("Read the task contract before editing code."),
      bullet("Keep changes scoped to the selected task."),
      bullet("Run quality checks before claiming completion."),
      bullet("Use the task board to sync PROGRESS.md after meaningful status changes."),
      "",
      "## Active Work",
      "",
      overview.nextTask
        ? bullet(`Current focus task: ${overview.nextTask.title}`)
        : bullet("Pick a Ready task from the board."),
      ""
    ].join("\n"),
    "PROMPTS.md": [
      title(`${projectName} Prompts`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Templates",
      "",
      bullet("Implementation — build from task contract fields."),
      bullet("Review — inspect changes against acceptance criteria."),
      bullet("Fix — include failed quality output and original task context."),
      bullet("Test — focus on quality commands and verification."),
      bullet("Security — review risky commands and data handling."),
      ""
    ].join("\n"),
    "KNOWN_ISSUES.md": [
      title(`${projectName} Known Issues`),
      `Generated by AgentDesk on ${generatedAt}.`,
      "",
      "## Open Issues",
      "",
      taskSummary.failed > 0
        ? bullet(`${taskSummary.failed} task(s) are currently marked Failed.`)
        : bullet("No failed tasks recorded."),
      taskSummary.blocked > 0
        ? bullet(`${taskSummary.blocked} task(s) are currently Blocked.`)
        : bullet("No blocked tasks recorded."),
      "",
      "## Risks",
      "",
      bullet("CLI agents may not be installed on PATH."),
      bullet("Terminal and git features require local tooling on Windows."),
      ""
    ].join("\n")
  };

  return sections[fileName] ?? `${title(fileName.replace(".md", ""))}\nGenerated by AgentDesk on ${generatedAt}.\n`;
};
